#!/usr/bin/env python3
"""
PE Sourcing Engine v5.7 - Docker Installer
Standardized setup matching dg production environment
"""

import os
import sys
import subprocess
import secrets
import time
from pathlib import Path

def run_command(command, ignore_errors=False):
    """Execute shell command"""
    try:
        subprocess.run(command, shell=True, check=True)
        return True
    except subprocess.CalledProcessError:
        if not ignore_errors:
            print(f"❌ Error running: {command}")
        return False

def prompt(question, default=None):
    """Prompt user for input with optional default"""
    if default:
        val = input(f"{question} [{default}]: ").strip()
        return val if val else default
    else:
        val = input(f"{question}: ").strip()
        return val

def check_docker():
    """Check if Docker and Compose are installed"""
    if not run_command("docker --version", ignore_errors=True):
        print("❌ Docker not found. Please install Docker first.")
        print("   Ubuntu/Debian: sudo apt-get install docker.io docker-compose-plugin")
        print("   Fedora: sudo dnf install docker docker-compose-plugin")
        sys.exit(1)
    
    if not run_command("docker compose version", ignore_errors=True):
        print("❌ Docker Compose v2 not found. Please install docker-compose-plugin.")
        sys.exit(1)
    
    print("✅ Docker and Docker Compose found")

def create_env_file():
    """Create .env file with user input"""
    env_path = Path(".env")
    
    existing = {}
    if env_path.exists():
        print("\n📄 Existing .env found. Loading current values...")
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing[key.strip()] = value.strip()
    
    print("\n--- 🗄️ Database Configuration ---")
    db_pass = prompt("Database Password", existing.get("DB_PASS") or secrets.token_urlsafe(16))
    
    print("\n--- 🔐 Security Secrets ---")
    jwt_secret = prompt("JWT Secret (auto-generated if blank)", existing.get("JWT_SECRET_KEY") or secrets.token_hex(32))
    csrf_secret = prompt("CSRF Secret (auto-generated if blank)", existing.get("CSRF_SECRET") or secrets.token_hex(32))
    
    print("\n--- 🔑 API Keys (can be added later via Admin dashboard) ---")
    google_places = prompt("Google Places API Key", existing.get("GOOGLE_PLACES_API_KEY", ""))
    gemini = prompt("Google Gemini API Key", existing.get("GEMINI_API_KEY", ""))
    serper = prompt("Serper API Key", existing.get("SERPER_API_KEY", ""))
    
    env_content = f"""# PE Sourcing Engine v5.7 - Environment Variables
# Generated by installer

# Database
DB_USER=pe_sourcer
DB_PASS={db_pass}
DB_NAME=pe_sourcing_db

# Authentication
JWT_SECRET_KEY={jwt_secret}
CSRF_SECRET={csrf_secret}

# API Keys
GOOGLE_PLACES_API_KEY={google_places}
GEMINI_API_KEY={gemini}
SERPER_API_KEY={serper}
"""
    
    env_path.write_text(env_content)
    print("✅ .env file created")

def validate_env():
    """Validate required environment variables"""
    print("\n🔍 Validating configuration...")
    
    with open(".env", 'r') as f:
        content = f.read()
    
    required = ["DB_PASS", "JWT_SECRET_KEY", "CSRF_SECRET"]
    missing = []
    for key in required:
        if f"{key}=" not in content:
            missing.append(key)
        else:
            value = content.split(f"{key}=")[1].split("\n")[0].strip()
            if not value:
                missing.append(key)
    
    if missing:
        print(f"❌ Missing required variables: {', '.join(missing)}")
        sys.exit(1)
    
    # Check optional API keys
    optional = ["GOOGLE_PLACES_API_KEY", "GEMINI_API_KEY", "SERPER_API_KEY"]
    missing_optional = []
    for key in optional:
        if f"{key}=" in content:
            value = content.split(f"{key}=")[1].split("\n")[0].strip()
            if not value:
                missing_optional.append(key)
    
    if missing_optional:
        print(f"⚠️  Optional API keys not set: {', '.join(missing_optional)}")
        print("   You can add these via the Admin dashboard after login.")
    
    print("✅ Configuration valid")

def main():
    print("\n" + "="*60)
    print("🚀 PE Sourcing Engine v5.7 - Docker Installer")
    print("="*60)
    
    # Change to script directory
    os.chdir(Path(__file__).parent)
    
    check_docker()
    create_env_file()
    validate_env()
    
    print("\n--- 🔨 Building and Starting Services ---")
    proceed = prompt("Build and start containers now? (y/n)", "y")
    
    if proceed.lower() != 'y':
        print("\n✅ Configuration saved. Run these commands when ready:")
        print("   cd docker-v5.7")
        print("   docker compose -f docker-compose-v5.7.yml up -d")
        sys.exit(0)
    
    # Build and start
    if not run_command("docker compose -f docker-compose-v5.7.yml build"):
        print("❌ Build failed. Check error messages above.")
        sys.exit(1)
    
    if not run_command("docker compose -f docker-compose-v5.7.yml up -d"):
        print("❌ Failed to start containers.")
        sys.exit(1)
    
    # Wait for database
    print("\n⏳ Waiting for database to be ready...")
    time.sleep(10)
    
    print("\n" + "="*60)
    print("✅ Installation Complete!")
    print("="*60)
    print(f"\n📊 Dashboard: http://localhost:8000")
    print(f"\n🔐 Default Login:")
    print(f"   Email: admin@dealgenome.local")
    print(f"   Password: admin123")
    print(f"   ⚠️  CHANGE THIS PASSWORD IMMEDIATELY!")
    print(f"\n🛠️  Useful Commands:")
    print(f"   View logs:    docker compose -f docker-compose-v5.7.yml logs -f app")
    print(f"   Stop:         docker compose -f docker-compose-v5.7.yml down")
    print(f"   Restart app:  docker compose -f docker-compose-v5.7.yml restart app")
    print("\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Installation cancelled.")
        sys.exit(1)
